#:kivy 1.0

<Controller>:

    screen_main: screen_main_id

    orientation: 'horizontal'
    padding: 20

    BoxLayout:
        id: screen_main_id

        Button:
            id: bd_button
            text: "Bases de datos"
            on_press: root.screen_bd()

        Button:
            id: analysis_button
            text: "Análisis"

        Button:
            text: "FAQ"

        Button:
            text: "Créditos"
